// This file is auto-generated by imageImporter.ts
// Do not edit this file directly
import bpctbfmilf from "./original/436332565_3882301978761234_1854758056395920990_n.jpg";
import estppvkhrs from "./original/ZAI03235.jpg";
import jrelmrzxwi from "./original/ZAI03242.jpg";
import gztifbxokr from "./original/ZAI03273 copy.jpg";
import sdgrkbddvs from "./original/ZAI03273.jpg";
import hpzndhmsou from "./original/ZAI03322.jpg";
import oitcphfzun from "./original/ZAI03429.jpg";
import thilwcpehr from "./original/ZAI03584.jpg";
import gyjfurbkrd from "./original/ZAI03597.jpg";
import mvisnylnto from "./original/ZAI03648.jpg";
import iduadxrczt from "./original/ZAI03660.jpg";
import ocxbnwwkun from "./original/ZAI03746-Enhanced-NR.jpg";
import utjhxebwgq from "./original/ZAI03747.jpg";
import arenzyfujb from "./original/ZAI03780.jpg";
import kiyouqkmee from "./original/ZAI03816.jpg";
import jqglomhlwi from "./original/ZAI03866-Enhanced-NR.jpg";
import vkdlvwgiqc from "./original/ZAI03953.jpg";
import zrvgzsspfs from "./original/ZAI04336.jpeg";
import vobsmrevqc from "./original/ZAI04379.jpeg";
import jcgxlcwikh from "./original/ZAI04397.jpg";
import rqyrlyndxo from "./original/ZAI04446.jpeg";

const imageList: Record<string, ImageMetadata> = {
	bpctbfmilf: bpctbfmilf,
	estppvkhrs: estppvkhrs,
	jrelmrzxwi: jrelmrzxwi,
	gztifbxokr: gztifbxokr,
	sdgrkbddvs: sdgrkbddvs,
	hpzndhmsou: hpzndhmsou,
	oitcphfzun: oitcphfzun,
	thilwcpehr: thilwcpehr,
	gyjfurbkrd: gyjfurbkrd,
	mvisnylnto: mvisnylnto,
	iduadxrczt: iduadxrczt,
	ocxbnwwkun: ocxbnwwkun,
	utjhxebwgq: utjhxebwgq,
	arenzyfujb: arenzyfujb,
	kiyouqkmee: kiyouqkmee,
	jqglomhlwi: jqglomhlwi,
	vkdlvwgiqc: vkdlvwgiqc,
	zrvgzsspfs: zrvgzsspfs,
	vobsmrevqc: vobsmrevqc,
	jcgxlcwikh: jcgxlcwikh,
	rqyrlyndxo: rqyrlyndxo,
};

export default imageList;
